Revert "Update the read write calls with nsid"
Error:

19:22:05  hw/vssim/simulator/vssim_config_manager.c: In function 'set_device_object':
19:22:05  hw/vssim/simulator/vssim_config_manager.c:294:22: error: 'SECTOR_NB' undeclared (first use in this function)
19:22:05    device->sector_nb = SECTOR_NB;
19:22:05                        ^
19:22:05  hw/vssim/simulator/vssim_config_manager.c:294:22: note: each undeclared identifier is reported only once for each function it appears in
19:22:05  hw/vssim/simulator/vssim_config_manager.c: In function 'clear_globals':
19:22:05  hw/vssim/simulator/vssim_config_manager.c:350:5: error: 'SECTOR_NB' undeclared (first use in this function)
19:22:05       SECTOR_NB = 0;
19:22:05       ^

introduced by https://review.gerrithub.io/c/davidsaOpenu/simulator/+/1217080

This reverts commit 483e9f10a3921b8fe3b2f31af4ff33ae6c7cd1bb.

Change-Id: I93445e689819d903eb7e378983dc972dd613edc2