Revert "Add json-c library support for the json serialization mechannism"
Reverted to fix the lookup for 32-bit versions of json-c
while on 64-bit hosts. The error message was somewaht unrealed:

  ERROR: sizeof(size_t) doesn't match GLIB_SIZEOF_SIZE_T.
         You probably need to set PKG_CONFIG_LIBDIR
         to point to the right pkg-config files for your
         build target.

but the root cause was 32-bit vs 64-bit libs.

This reverts commit 1f269572896f51b3cb049e1d978baf9a53fefe06.

Change-Id: I01109c4030d2215554d57db3098dd2aae702fa62